# Generated by Django 2.2 on 2019-04-23 01:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=64)),
                ('max_cloud_cover', models.IntegerField(null=True)),
                ('begin_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('wgs_row', models.IntegerField(null=True)),
                ('wgs_path', models.IntegerField(null=True)),
                ('kml_polygon', models.TextField(null=True)),
                ('bounding_left', models.FloatField(null=True)),
                ('bounding_right', models.FloatField(null=True)),
                ('bounding_top', models.FloatField(null=True)),
                ('bounding_bottom', models.FloatField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('associated_workflow_id', models.IntegerField(null=True)),
                ('associated_subject_set_id', models.IntegerField(null=True)),
                ('multiple_subject_sets', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_entity_id', models.CharField(max_length=64)),
                ('scene_order_id', models.CharField(max_length=128)),
                ('scene_url', models.CharField(max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_at', models.DateTimeField(db_index=True, null=True)),
                ('imagery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ImageryRequest')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('operation', models.CharField(max_length=64)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='imageryrequest',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pipeline'),
        ),
        migrations.AddField(
            model_name='imageryrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
