# Generated by Django 2.2.1 on 2019-05-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_entity_id', models.CharField(max_length=64)),
                ('current_stage_index', models.IntegerField(default=0)),
                ('total_stages', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('hostname', models.CharField(default='', max_length=128)),
                ('local_path', models.CharField(default='', max_length=512)),
                ('dir_size', models.IntegerField(default=0)),
                ('hearbeat', models.DateTimeField(null=True)),
                ('current_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PipelineStage')),
                ('imagery_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ImageryRequest')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pipeline')),
                ('requested_scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.RequestedScene')),
            ],
        ),
    ]
