# Generated by Django 2.2 on 2019-04-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageryrequest',
            name='pending_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageryrequest',
            name='status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='RequestedScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_url', models.CharField(max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('imagery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ImageryRequest')),
            ],
        ),
    ]
