# Generated by Django 2.2 on 2019-04-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190422_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedscene',
            name='scene_entity_id',
            field=models.CharField(default='No Id', max_length=64),
        ),
    ]
