# Generated by Django 2.2.1 on 2019-05-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190503_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ['pipeline', 'sort_order']},
        ),
    ]
