# Generated by Django 2.2.1 on 2019-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190513_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageryrequest',
            name='adapter_name',
            field=models.CharField(default='usgs', max_length=64),
        ),
    ]
