# Generated by Django 2.2.1 on 2019-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imageryrequest_adapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageryrequest',
            name='adapter_name',
            field=models.CharField(max_length=64),
        ),
    ]
