# Generated by Django 2.2.1 on 2019-05-14 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190513_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='select_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
    ]
