# Generated by Django 2.2.1 on 2019-05-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190514_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageryrequest',
            name='create_subject_set',
        ),
        migrations.RemoveField(
            model_name='imageryrequest',
            name='subject_set_id',
        ),
        migrations.AddField(
            model_name='jobbundle',
            name='subject_set_id',
            field=models.IntegerField(null=True),
        ),
    ]
