# Generated by Django 2.2.1 on 2019-05-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190515_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='associated_subject_set_id',
            new_name='subject_set_id',
        ),
        migrations.RenameField(
            model_name='pipeline',
            old_name='associated_workflow_id',
            new_name='workflow_id',
        ),
    ]
