# Generated by Django 2.2.4 on 2019-12-08 18:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_imageryrequest_max_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageryrequest',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='bounding_bottom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='bounding_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='bounding_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='bounding_top',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='status',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='output_format',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
