# Generated by Django 2.2.4 on 2019-12-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageryrequest',
            name='kml_polygon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
