# Generated by Django 2.2.4 on 2020-01-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191210_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(max_length=256)),
                ('bearer_expiry', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
    ]
