# Generated by Django 2.2.4 on 2020-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AddField(
            model_name='imageryrequest',
            name='bearer_expiry',
            field=models.CharField(default=1, editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageryrequest',
            name='bearer_token',
            field=models.CharField(default=2, editable=False, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageryrequest',
            name='refresh_token',
            field=models.CharField(default=2, editable=False, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='username',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
