# Generated by Django 2.2.4 on 2020-01-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200121_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageryrequest',
            name='bearer_expiry',
            field=models.CharField(default='TESTO', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='bearer_token',
            field=models.CharField(default='tist', editable=False, max_length=2048),
        ),
        migrations.AlterField(
            model_name='imageryrequest',
            name='refresh_token',
            field=models.CharField(default='TAST', editable=False, max_length=512),
        ),
    ]
