# Generated by Django 2.2.4 on 2020-03-13 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200122_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='imageryrequest',
            name='bearer_expiry',
        ),
        migrations.RemoveField(
            model_name='imageryrequest',
            name='bearer_token',
        ),
        migrations.RemoveField(
            model_name='imageryrequest',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='jobbundle',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobbundle_current_stage', to='api.PipelineStage'),
        ),
    ]
