# Generated by Django 2.2 on 2019-04-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=64)),
                ('max_cloud_cover', models.IntegerField(null=True)),
                ('begin_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('wgs_row', models.IntegerField(null=True)),
                ('wgs_path', models.IntegerField(null=True)),
                ('kml_polygon', models.TextField()),
                ('bounding_left', models.FloatField(null=True)),
                ('bounding_right', models.FloatField(null=True)),
                ('bounding_top', models.FloatField(null=True)),
                ('bounding_bottom', models.FloatField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(db_index=True)),
                ('multiple_subject_sets', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
